# Generated by Django 4.1.3 on 2022-11-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('guess_characters', models.CharField(max_length=50)),
                ('max_guess', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_guess', models.IntegerField(default=0)),
                ('player_guess', models.CharField(default=' ', max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'InProgress'), (2, 'Lost'), (3, 'Won')], default=1)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.words')),
            ],
        ),
    ]
